### ISSUE TITLE
Issue in connecting to a remote Quartz.Net scheduler (windows service)

### ISSUE THREAD

**Issue by ghost** [mausch/QuartzNetWebConsole#22]
For testing I'm running the Quartz.net scheduler as windows service under the same box, where my web-app (having embedded quartznet web console) is also hosted.

Problem description:

The windows service is started manually and runs fine with logging and adojobstore.

The web app has the following code to initialize the quartz.net web console to the quartz.net scheduler, and also runs fine without any exception:

NameValueCollection properties = new NameValueCollection();
properties["quartz.scheduler.instanceName"] = "SPDQuartzScheduler";

// set thread pool info
properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
properties["quartz.threadPool.threadCount"] = "10";
properties["quartz.threadPool.threadPriority"] = "Normal";

// set remoting expoter
properties["quartz.scheduler.proxy"] = "true";
properties["quartz.scheduler.proxy.address"] = "tcp://localhost:555/SPDQuartzScheduler";

 // First we must get a reference to a scheduler
 ISchedulerFactory sf = new StdSchedulerFactory(properties);
 quartzScheduler = sf.GetScheduler();

 //Assign webconsole to scheduler
 QuartzNetWebConsole.Setup.Scheduler = () => quartzScheduler;

When we visit the ..\quartz\index.html page in the web app, the following exception is thrown:

Quartz.SchedulerException: Operation not supported for remote schedulers.
   at Quartz.Impl.RemoteScheduler.get_ListenerManager()
   at QuartzNetWebConsole.Utils.SchedulerWrapper.get_ListenerManager()
   at QuartzNetWebConsole.Controllers.IndexController.Execute(HttpContextBase context, Func`1 getScheduler)
   at QuartzNetWebConsole.ControllerFactory.<.ctor>b__6(HttpContextBase ctx)
   at MiniMVC.HttpHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by alexminza** [comment]
What is the correct way to connect to a remote scheduler?

We run Quartz.net in a clustered environment with ```Quartz.Impl.AdoJobStore.JobStoreTX``` job store and export it with ```Quartz.Simpl.RemotingSchedulerExporter```.

Here is the code setup in the QuartzNetWebConsole app:

```
        protected void Application_Start(object sender, EventArgs e)
        {
            #region QuartzNetWebConsole remote scheduler setup

            var quartzProperties = new NameValueCollection();
            quartzProperties["quartz.scheduler.instanceName"] = ConfigurationManager.AppSettings["QuartzSchedulerName"];
            quartzProperties["quartz.scheduler.instanceId"] = Environment.GetEnvironmentVariable("RoleInstanceID") ?? Environment.MachineName; //"AUTO"

            //avoid running any jobs locally
            quartzProperties["quartz.threadPool.type"] = "Quartz.Simpl.ZeroSizeThreadPool, Quartz";
            quartzProperties["quartz.threadPool.threadCount"] = "0";

            quartzProperties["quartz.scheduler.proxy"] = "true";
            quartzProperties["quartz.scheduler.proxy.address"] = ConfigurationManager.AppSettings["QuartzProxyAddress"];

            var schedulerFactory = new StdSchedulerFactory();
            var scheduler = schedulerFactory.GetScheduler();

            QuartzNetWebConsole.Setup.Scheduler = () => scheduler;

            #endregion
        }
```

```QuartzSchedulerName``` setting is the same as the clustered schedulers. ```QuartzProxyAddress``` is the same as we use for the CrystalQuartz console.

However, QuartzNetWebConsole displays a blank page:

![screen shot 2015-02-19 at 18 19 56](https://cloud.githubusercontent.com/assets/149919/6270728/709acf86-b864-11e4-9915-5e35d0cd0172.png)

What are we doing wrong? Is this scenario supported?

**Comment by mausch** [comment]
I've never needed to connect to a remote Quartz instance. The comments here outline a solution/implementation for some of it. 
In your particular case, it seems as if `IsTriggerGroupPaused` is not supported in a remoting scenario. It is not clear to me what is and isn't supported in a remoting scenario.
In addition to that, not all job stores support every action in the interface, which leads to issues like https://github.com/mausch/QuartzNetWebConsole/issues/18 . Again, it's not clear what's supported and what's not. 
So for a proper solution someone would have to write exhaustive tests for all methods in the interface with remoting / different job stores.

**Comment by andreidobre** [comment]
Hello and good day!
Is it possible to connect remotely to another quartz server using the IP address?
To be more precise: I have listed a few jobs in the quartz_jobs.xml and they are triggered at the specified hours by the scheduler. In this case, I use the windows service to execute the jobs. 
I want to make another external application (independent from the quartz DLL) from where I can execute immediately one of the jobs from my quartz_jobs.xml file. I want to access the service and pass him two parameters, the name of the job and let's say the IP address of the server. I don't want to use the quartz.scheduler.proxy.address because this will intrefier with my config files. I want this external application to be as independent as possible.
Is it possible, or the proxy.address is the only way?


Thank you for your time,
Dobre Andrei

**Comment by mausch** [comment]
@andreidobre  please use the [Quartz.NET mailing list](https://groups.google.com/forum/#!forum/quartznet) for any questions about Quartz.NET.

**Comment by andreidobre** [comment]
thank you
