### ISSUE TITLE
dnxcore50 Support

### ISSUE THREAD

**Issue by peder** [mausch/QuartzNetWebConsole#28]
I created a new project with ASP.NET 5 RC, and I cannot add `QuartzNetWebConsole.Owin` as Studio's complaining that it's not compatible with `DNXCore` v5. Any recommendations for working around this?

**Comment by mausch** [comment]
Is Quartz.NET compatible with .NET Core?
I honestly haven't looked into .NET Core in detail. QuartzNetWebConsole.Owin is regular old .NET 4.5 assembly. I assume .NET Core is just another target? i.e. could you get the code and simply make it compile against .NET Core?

**Comment by mausch** [comment]
Done in https://github.com/mausch/QuartzNetWebConsole/commit/1ae0ef15863eecd9e6fea3f8949fe4172d26e39f
